consultorio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion_consultorio.urls') )
]

gestion_consultorio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('pacientes', views.pacientes, name='pacientes'),
    path('<int:paciente_id>/pedidos', views.pedidos, name='pedidos'),
    path('ventas', views.ventas, name='ventas'),
    path('turnos', views.turnos, name='turnos'),
    path("<int:paciente_id>/eliminar_paciente", views.eliminar_paciente, name="eliminar_paciente"),
    path("<int:paciente_id>/historia_clinica", views.historia_clinica, name="historia_clinica"),
    path("<int:turno_id>/atender_paciente", views.atender_paciente, name="atender_paciente"),
    path("login", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("errorpermisos", views.errorpermisos, name="errorpermisos"),
    path("graba_hclinica", views.graba_hclinica, name="graba_hclinica"),
    path("<int:turno_id>/ausente_paciente", views.ausente_paciente, name="ausente_paciente"),
    path("<int:turno_id>/eliminar_turno", views.eliminar_turno, name="eliminar_turno"),
    path("<int:paciente_id>/agregar_articulo", views.agregar_articulo, name="agregar_articulo"),
    path("<int:producto_id>/<int:paciente_id>/venta_temp", views.venta_temp, name="venta_temp"),
    path("<int:producto_id>/<int:paciente_id>/eliminar_articulo", views.eliminar_articulo, name="eliminar_articulo"),
    path("<int:venta_id>/detalle_venta", views.detalleventa, name="detalleventa"),
    path("taller", views.taller, name="taller"),
    path("gerencia", views.gerencia, name="gerencia"),
    path("<int:venta_id>/finalizar_pedido", views.finalizar_pedido, name="finalizar_pedido"),
    path("<str:seleccion>/<str:rango>/informe_paciente", views.informe_paciente, name="informe_paciente"),
    path("<str:seleccion>/<str:rango>/informe_paciente", views.informe_paciente, name="informe_paciente"),
    path("ausente/mes/informe_paciente", views.informe_paciente, name="informe_paciente"),
    path("ausente/semana/informe_paciente", views.informe_paciente, name="informe_paciente"),
    path("compra/mes/informe_paciente", views.informe_paciente, name="informe_paciente"),
    path("compra/semana/informe_paciente", views.informe_paciente, name="informe_paciente"),
    path("mas_vendidos", views.mas_vendidos, name="mas_vendidos"),
    path("ventas_por_vendedor", views.ventas_por_vendedor, name="ventas_por_vendedor"),   
]

gestion_consultorio/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

class paciente(models.Model):
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class medico(models.Model):
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class turno(models.Model):
    id_paciente = models.ForeignKey(paciente, on_delete=models.CASCADE)
    fecha_turno =  models.DateField()
    hora_turno =  models.TimeField()
    id_medico = models.ForeignKey(medico, on_delete=models.CASCADE)
    estado_turno = models.CharField(max_length=32, default='PENDIENTE', choices=[('PENDIENTE','pendiente'),('AUSENTE','ausente'),('ATENDIDO','atendido')])

class historia_medica(models.Model):
    id_paciente = models.ForeignKey(paciente, on_delete=models.CASCADE)
    id_medico = models.ForeignKey(medico, on_delete=models.CASCADE)
    fecha = models.DateField()
    descripcion = models.TextField(blank=True)


class producto(models.Model):
    nombre_producto = models.CharField(max_length=64)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    clasificacion = models.CharField(max_length=32, choices=[('LENTE','lente'),('ACCESORIO','accesorio'),('ETC','etc')])
    distacia_vision = models.CharField(max_length=10,choices=[('LEJOS','lejos'),('CERCA','cerca')])
    ojo_vision = models.CharField(max_length=32, choices=[('IZQUIERDO','izquierdo'),('DERECHO','derecho')])
    armazon = models.CharField(max_length=2,default="NO")

class venta(models.Model):
    id_paciente = models.ForeignKey(paciente, on_delete=models.CASCADE)
    fecha_venta = models.DateField(default=datetime.datetime(2000,1,31))
    total_vent = models.DecimalField(max_digits=8, decimal_places=2)
    id_User = models.ForeignKey(User, on_delete = models.CASCADE, blank=True)
    forma_de_pago = models.CharField(max_length=32, choices=[('EFECTIVO','efectivo'),('TARJETA DE CREDITO','tarjeta de credito'),('DEBITO','debito'),('BILLETERA VIRTUAL','billetera virtual')],blank=True)
    estado = models.CharField(max_length=32, choices=[('PENDIENTE','pendiente'),('PEDIDO','pedido'),('FINALIZADO','finalizado')],default="PENDIENTE")

class detalle_venta(models.Model):
    id_venta = models.ManyToManyField(venta)
    id_producto = models.ForeignKey(producto, on_delete=models.CASCADE)

class venta_temporal(models.Model):
    id_producto = models.ForeignKey(producto, on_delete=models.CASCADE)

gestion_consultorio/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect    
from .models import paciente, medico, turno, historia_medica, producto, venta_temporal, venta, detalle_venta
from django import forms
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from datetime import timedelta
import datetime
from django.db.models import Sum,Count,Q


@login_required(login_url='login_view')
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login_view"))
    else: 
        return render(request,"index.html")
   

def errorpermisos(request):
    return render(request,"errorpermisos.html")


def acceso_pacientes(user):
    #define que grupos pueden acceder a la vista de pacientes
    return user.groups.filter(name__in=['Medicos','Secretarias']).exists()
    

@login_required(login_url='login_view')
@user_passes_test(acceso_pacientes, login_url='errorpermisos')
def pacientes(request):
    if request.method == "POST":
        form = FormNuevoPaciente(request.POST)
        if form.is_valid():
            p = paciente()
            p.nombre = form.cleaned_data["nombre"]
            p.apellido = form.cleaned_data["apellido"]
            p.save()
            return HttpResponseRedirect(reverse('pacientes'))
        
        if request.POST['id_post'] == "form_nuevo_turno":
            t = turno()
            t.id_paciente=paciente.objects.get(pk=int(request.POST['id_paciente']))
            t.id_medico=medico.objects.get(pk=int(request.POST['id_medico']))
            t.hora_turno=request.POST['hora_turno']
            t.fecha_turno=request.POST['fecha_turno']
            t.save()
            return HttpResponseRedirect(reverse('pacientes'))

        if request.POST['id_post'] == "form_editar_paciente":
            p = paciente()
            p = paciente.objects.get(pk=int(request.POST['id_paciente']))
            p.nombre=request.POST['nombre_paciente']
            p.apellido=request.POST['apellido_paciente']
            p.save()
            return HttpResponseRedirect(reverse('pacientes'))
    
    return render(request,"pacientes.html", {"medicos":medico.objects.all(),"pacientes": paciente.objects.all().order_by('apellido'), "form": FormNuevoPaciente()})

def acceso_pedidos(user):
    #define que grupos pueden acceder a la vista de turnos
    return user.groups.filter(name__in=['Vendedores']).exists()

@login_required(login_url='login_view')
@user_passes_test(acceso_pedidos, login_url='errorpermisos')
def pedidos(request,paciente_id):
    subtotal=venta_temporal.objects.aggregate(Sum('id_producto__precio'))
    return render(request,"pedidos.html",{"paciente": paciente.objects.get(pk=paciente_id), "pedido_actual": venta_temporal.objects.all(), "subtotal": subtotal})

def acceso_ventas(user):
    #define que grupos pueden acceder a la vista de turnos
    return user.groups.filter(name__in=['Vendedores']).exists()

@login_required(login_url='login_view')
@user_passes_test(acceso_ventas, login_url='errorpermisos')
def ventas(request):
    if request.method == "POST":
        v = venta()
        v.id_paciente = paciente.objects.get(pk=int(request.POST['id_paciente']))
        v.fecha_venta = datetime.date.today()
        v.total_vent = request.POST['total_venta']
        v.id_User = request.user
        if request.POST['opcion_pago']=="efectivo":
            v.forma_de_pago="EFECTIVO"
        elif request.POST['opcion_pago']=="tcredito":
            v.forma_de_pago="TARJETA DE CREDITO"
        elif request.POST['opcion_pago']=="tdebito":
            v.forma_de_pago="DEBITO"
        elif request.POST['opcion_pago']=="virtual":
            v.forma_de_pago="BILLETERA VIRTUAL"
        
        if 'taller' in request.POST:
            v.estado="PEDIDO"
        else:
            v.estado="FINALIZADO"

        v.save()
        venta_id=v.pk

        vtemp = venta_temporal.objects.all()
        for vt in vtemp:
            idpro=int(vt.id_producto.id)
            id_producto=producto.objects.get(pk=idpro)
            movimiento=detalle_venta.objects.create(id_producto=id_producto)
            movimiento.id_venta.add(venta_id)
        venta_temporal.objects.all().delete()
    else:
        venta_temporal.objects.all().delete()
    return render(request,"ventas.html",{"pacientes": paciente.objects.all().order_by('apellido','nombre')})

def agregar_articulo(request,paciente_id):
    return render(request,"agregar_articulo.html",{"productos": producto.objects.all(), "paciente":paciente_id})

def eliminar_articulo(request,producto_id,paciente_id):
    venta_temporal.objects.get(pk=producto_id).delete()
    return HttpResponseRedirect(reverse('pedidos', args=[paciente_id]))


def venta_temp(request,producto_id,paciente_id):
    venta=venta_temporal()
    venta.id_producto=producto.objects.get(pk=int(producto_id))
    venta.save() 
    return HttpResponseRedirect(reverse('pedidos', args=[paciente_id]))


def acceso_turnos(user):
    #define que grupos pueden acceder a la vista de turnos
    return user.groups.filter(name__in=['Medicos','Secretarias']).exists()
    
@login_required(login_url='login_view')
@user_passes_test(acceso_turnos, login_url='errorpermisos')
def turnos(request):
    hoy=datetime.date.today()
    fecha_filtro = {'fecha_turno': hoy}
    if request.method == "POST":
        if request.POST['id_post'] == "form_editar_turno":
            t = turno()
            t = turno.objects.get(pk=int(request.POST['id_turno']))
            t.id_medico=medico.objects.get(pk=int(request.POST['id_medico']))
            t.hora_turno=request.POST['hora_turno']
            t.fecha_turno=request.POST['fecha_turno']
            t.save()
            return HttpResponseRedirect(reverse('turnos'))
        
        elif request.POST['id_post'] == "form_filtrar_turno":
            fecha_dividida=request.POST['fecha'].split("-")
            if request.POST['opcion_fecha_filtro']=="dia":
                fecha_filtro = {'fecha_turno': request.POST['fecha']}
            elif request.POST['opcion_fecha_filtro']=="mes":
                fecha_filtro = {'fecha_turno__month': fecha_dividida[1], 'fecha_turno__year': fecha_dividida[0]}
            elif request.POST['opcion_fecha_filtro']=="anio":
                fecha_filtro = {'fecha_turno__year': fecha_dividida[0]}
            elif request.POST['opcion_fecha_filtro']=="todos":
                fecha_filtro = {}


    usuario = None
    if request.user.is_authenticated:
        usuario_nombre = request.user.first_name
        usuario_apellido = request.user.last_name
        try:
            medico_filtro=medico.objects.get(nombre=usuario_nombre,apellido=usuario_apellido)
            consulta = turno.objects.filter(id_medico=medico_filtro).filter(**fecha_filtro).order_by('fecha_turno','hora_turno')
        except: 
            consulta = turno.objects.filter(**fecha_filtro).order_by('fecha_turno','hora_turno')
    return render(request,"turnos.html", {"medicos":medico.objects.all(),"turnos": consulta})

def acceso_eliminar_pacientes(user):
    #define que grupos pueden acceder a la vista de elipacientes
    return user.groups.filter(name__in=['Secretarias']).exists()
   
@login_required(login_url='login_view')
@user_passes_test(acceso_eliminar_pacientes, login_url='errorpermisos')
def eliminar_paciente(request, paciente_id):
    p =  paciente.objects.get(pk=paciente_id)
    p.delete()
    return HttpResponseRedirect(reverse('pacientes'))

@login_required(login_url='login_view')
def historia_clinica(request, paciente_id):
    return render(request,"historia_clinica.html",{"paciente":paciente.objects.get(pk=paciente_id),"historia_clinica": historia_medica.objects.filter(id_paciente=paciente_id)})

@login_required(login_url='login_view')
def atender_paciente(request, turno_id):
    paciente_id= turno.objects.get(pk=turno_id).id_paciente
    return render(request,"atender_paciente.html",{"turno":turno.objects.get(pk=turno_id),"historia_clinica": historia_medica.objects.filter(id_paciente=paciente_id)})

class FormNuevoPaciente(forms.Form):
    nombre = forms.CharField(label="Nombre")
    apellido =forms.CharField(label="Apellido")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "login.html", {
                "mensaje": "Credenciales no validas."
            })
    else:
        return render(request, "login.html")

def logout_view(request):
    logout(request)
    return render(request, "login.html", {"mensaje": "Desconectado."})

@login_required(login_url='login_view')
def graba_hclinica(request):
    if request.method == "POST":
        m = historia_medica()
        m.id_medico=turno.objects.get(pk=int(request.POST['id_turno'])).id_medico
        m.id_paciente=turno.objects.get(pk=int(request.POST['id_turno'])).id_paciente   
        m.fecha=request.POST['fecha']
        m.descripcion=request.POST['movimiento']
        m.save()
        id_turno=request.POST['id_turno']
        t = turno()
        t = turno.objects.get(pk=int(id_turno))
        t.estado_turno = "ATENDIDO"
        t.save()
    return HttpResponseRedirect(reverse('turnos'))

@login_required(login_url='login_view')
def ausente_paciente(request, turno_id):
    t = turno.objects.get(pk=turno_id)
    t.estado_turno = "AUSENTE"
    t.save()
    return HttpResponseRedirect(reverse('turnos'))

@login_required(login_url='login_view')
def eliminar_turno(request, turno_id):
    t = turno.objects.get(pk=turno_id)
    t.delete()
    return HttpResponseRedirect(reverse('turnos'))

gestion_consultorio/templates/agregar_articulo.html
{% extends "layout.html" %}
{% block body %}

<div class="container">
  <h1 style="color:white">Productos</h1>
  <p style="color:white">Utiliza la barra inferior para buscar productos. Luego agregalos al pedido actual</p>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1"><i class="fa fa-search"></i></span>
    </div>
    <input type="text" class="form-control" id="buscar_tabla" placeholder="Buscar..." aria-label="Username" aria-describedby="basic-addon1">
  </div>
</div>
<div class="container">
  <div id="div1" class ="col-md-12">
    <table border="1" class="table table-hover table-bordered bg-white table-sm">
      <thead class="thead-dark">             
        <tr>
          <th style="display:none;" scope="col">Id</th>
          <th scope="col">Descripcion</th>
          <th scope="col">Ojo</th>
          <th scope="col">Distancia</th>
          <th scope="col">Marco</th>
          <th scope="col">Precio</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody id="tabla_busqueda">
        {% for unProducto in productos %}
          <tr>
            <td style="display:none">{{unProducto.id}}</td>
            <td>{{unProducto.nombre_producto}}</td>
            <td>{{unProducto.ojo_vision}}
            <td>{{unProducto.distacia_vision}}
            <td>{{unProducto.armazon}}
            <td style="text-align:right">$ {{unProducto.precio}}</td>
            <td>
              <a href="{% url 'venta_temp' unProducto.id paciente %}" class="btn btn-success btn-sm" id="btn-Nueva_venta"><i class="fa fa-cart-plus" aria-hidden="true"></i> Agregar</a>                
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
// busqueda en tabla
    $(document).ready(function(){
      $("#buscar_tabla").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#tabla_busqueda tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
</script>

{% endblock %}

gestion_consultorio/templates/atender_paciente.html
{% extends "layout.html" %}
{% block body %}

<div class="container">
  <h1 style="color:white">Atencion</h1>
  <h2 style="color:white">Paciente: {{turno.id_paciente}}</h2>
  <div class="input-group mb-3">
</div>

<div class="container">
  <form action="{% url 'graba_hclinica' %}" method="post">
  {% csrf_token %} 
    <div>
      <label style="color:white;">Seleccione fecha:</label>&nbsp;&nbsp;&nbsp;<input type="date" name="fecha" id="input_fecha">
    </div>
    <br>
    <textarea name="movimiento" rows="4" cols="120" required placeholder="Ingrese aqui las observaciones..."></textarea>
    <input type="hidden" name="id_turno" value={{turno.id}}>
    <input type="submit" class="btn btn-success btn-sm" value="Finalizar Atencion">
  </form>
</div>
<br>
<div class="container">
  <label style="color:white;">Historia Clinica</label>
  <div id="div1" class ="col-md-12">
    <table border="1" class="table table-hover table-bordered bg-white table-sm">
      <thead class="thead-dark">             
        <tr>
          <th style="display:none;" scope="col">Id</th>
          <th scope="col">Fecha</th>
          <th scope="col">Medico</th>
          <th scope="col">Descripcion</th>
        </tr>
      </thead>
      <tbody id="tabla_historia_clinica">
      {% for movimiento in historia_clinica %}
        <tr>
          <td>{{movimiento.fecha|date:"d/m/Y"}}</td>
          <td>{{movimiento.id_medico}}</td>
          <td>{{movimiento.descripcion}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>  
  window.onload = function(){
    var fecha = new Date(); //Fecha actual
    var mes = fecha.getMonth()+1; //obteniendo mes
    var dia = fecha.getDate(); //obteniendo dia
    var anio = fecha.getFullYear(); //obteniendo año
    if(dia<10)
      dia='0'+dia; //agrega cero si el menor de 10
    if(mes<10)
      mes='0'+mes //agrega cero si el menor de 10
    document.getElementById('input_fecha').value=anio+"-"+mes+"-"+dia;
  }
</script>
{% endblock %}

gestion_consultorio/templates/detalle_venta.html
{% extends "layout.html" %}
{%block body%}

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;
<div class="container">
  <h1 style="color:white">Taller</h1>
  <h2 style="color:white">Detalle venta</h2>
  <div class="input-group mb-3">
  <input type="button" onclick="history.back()" class="btn btn-success btn-sm"  name="volver atrás"  value="volver a Pedidos">
</div>
<div class="container">
  <div id="div1" class ="col-md-12">
    <table border="1" class="table table-hover table-bordered bg-white table-sm">
      <thead class="thead-dark">             
        <tr>
          <th style="display:none;" scope="col">Id</th>
          <th scope="col">Articulos vendidos</th>
          <th scope="col">Clasificacion</th>
          <th scope="col">Distancia Vision</th>
          <th scope="col">Ojo</th>
          <th scope="col">Armazon</th>
        </tr>
      </thead>
      <tbody id="tabla_ventas">
        {% for unDetalle in detalle %}
          <tr>
            <td>{{unDetalle.id_producto.nombre_producto}}</td>
            <td>{{unDetalle.id_producto.clasificacion}}</td>
            <td>{{unDetalle.id_producto.distacia_vision}}</td>
            <td>{{unDetalle.id_producto.ojo_vision}}</td>
            <td>{{unDetalle.id_producto.armazon}}</td>
            
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{%endblock%}

gestion_consultorio/templates/pacientes.html
{% extends "layout.html" %}
{% block body %}

<div class="container">
  <h1 style="color:white">Pacientes</h1>
  {% if perms.gestion_consultorio.change_paciente %}
    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#nuevo_paciente"><i class="fa fa-user-plus" aria-hidden="true"></i> Nuevo Paciente</button>
  {% else %}
    <button type="button" class="btn btn-info btn-sm" disabled><i class="fa fa-user-plus" aria-hidden="true"></i> Nuevo Paciente</button>
  {% endif %}
  <p style="color:white">Utiliza la barra inferior para buscar pacientes por Id,Nombre,Apellido</p>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1"><i class="fa fa-search"></i></span>
    </div>
    <input type="text" class="form-control" id="buscar_tabla" placeholder="Buscar..." aria-label="Username" aria-describedby="basic-addon1">
  </div>
</div>
<div class="container">
  <div id="div1" class ="col-md-12">
    <table border="1" class="table table-hover table-bordered bg-white table-sm">
      <thead class="thead-dark">             
        <tr>
          <th style="display:none;" scope="col">Id</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellido</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody id="tabla_busqueda">
        {% for unPaciente in pacientes %}
          <tr>
            <td style="display:none;">{{unPaciente.id}}</td>
            <td>{{unPaciente.nombre}}</td>
            <td>{{unPaciente.apellido}}</td>
            <td>
              {% if perms.gestion_consultorio.change_paciente %}
              <!--crea los botones habilitados-->
                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#editar_paciente" onclick="editar_paciente(this);" value="{{unPaciente.id}},{{unPaciente.nombre}},{{unPaciente.apellido}}">Editar</button>
                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#nuevo_turno" onclick="mostrarvalor(this);" value="{{unPaciente.id}},{{unPaciente.nombre}},{{unPaciente.apellido}}">Nuevo turno</button>
                <a href="{% url 'historia_clinica' unPaciente.id %}" class="btn btn-info btn-sm">Hist. Clinica</a>
                <a href="{% url 'eliminar_paciente' unPaciente.id %}" class="btn btn-danger btn-sm btn-delete" id="btn-delete">Eliminar</a>                
              {% else %}
              <!--genera los botones vacios-->
                <button type="button" class="btn btn-info btn-sm" disabled>Editar</button>
                <button type="button" class="btn btn-success btn-sm" disabled>Nuevo turno</button>
                <a href="{% url 'historia_clinica' unPaciente.id %}" class="btn btn-info btn-sm">Hist. Clinica</a>
                <button href="" class="btn btn-danger btn-sm btn-delete" disabled>Eliminar</button>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<!-- ventana modal nuevo paciente -->
<div class="modal fade" id="nuevo_paciente" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Nuevo paciente</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form action="{% url 'pacientes' %}" method="post"> 
          {% csrf_token %}
          {{ form }}
      </div>
      <div class="modal-footer">
        <input type="submit" class="btn btn-primary" value="Guardar">
      </div>
      </form>
    </div>
  </div>
</div>

<!-- ventana modal editar paciente -->
<div class="modal fade" id="editar_paciente" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Editar paciente</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form action="{% url 'pacientes' %}" method="post"> 
          {% csrf_token %}
            <input type="hidden" value="form_editar_paciente" name="id_post">
            <input type="hidden" id="input_id_paciente_editar" name="id_paciente">
            <p>Nombre   <input type="text" id="input_nombre_paciente" name="nombre_paciente" maxlength="20" required></p>
            <p>Apellido <input type="text" id="input_apellido_paciente" name="apellido_paciente" maxlength="20" required></p>
      </div>
      <div class="modal-footer">
        <input type="submit" class="btn btn-primary" value="Guardar">
      </div>
      </form>
    </div>
  </div>
</div>

<!-- ventana modal nuevo turno -->
<div class="modal fade" id="nuevo_turno" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Nuevo turno</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p id="nombre_paciente"></p>
        <form action="{% url 'pacientes' %}" method="post">
          {% csrf_token %} 
          <input type="hidden" id="input_id_paciente_nuevo_turno" name="id_paciente">
          <input type="hidden" id="input_id_medico" name="id_medico">
          <input type="hidden" value="form_nuevo_turno" name="id_post">
          <p> Seleccione Fecha: <input type="date"  id="input_date" name="fecha_turno" required></p>
          <p> Seleccione Hora: <input type="time" id="input_time" name="hora_turno" required>
          <p> Seleccione Medico: <select name"medicos" onclick="select_medico()" id="tabla_medico"></p>
          {% for unMedico in medicos %}
            <option class="option" value={{unMedico.id}}>{{unMedico.nombre }} {{unMedico.apellido}}</option> 
          {% endfor %}
          </select>
      </div>
          <div class="modal-footer">
            <input type="submit" class="btn btn-primary" value="Guardar">
          </div>
        </form>
    </div>
  </div>
</div>
<script>
// busqueda en tabla
    $(document).ready(function(){
      $("#buscar_tabla").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#tabla_busqueda tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });

    function editar_paciente(boton){
      var str = boton.value;
      var res = str.split(",");
      document.getElementById("input_id_paciente_editar").value=res[0];
      document.getElementById("input_nombre_paciente").value=res[1];
      document.getElementById("input_apellido_paciente").value=res[2];
    }
    function mostrarvalor(boton){
      var str = boton.value;
      var res = str.split(",");
      document.getElementById("input_id_paciente_nuevo_turno").value=res[0];
      document.getElementById("nombre_paciente").innerHTML="Nuevo turno Paciente: "+res[1]+" "+res[2];
      
      var id_medico = document.getElementById("tabla_medico");
      document.getElementById("input_id_medico").value=id_medico.value;
    }

    function select_medico(){
      var id_medico = document.getElementById("tabla_medico");
      document.getElementById("input_id_medico").value=id_medico.value;
    }
</script>
{% endblock %}